version: '3'
services:
      flask-app:
                container_name: flask-container    
                image: flask-image                      # to provide image name 
                build:
                    context: .
                ports:
                    - 5000:5000
                networks:
                    - flask-nw
                depends_on:
                     - mysql-app
           
      mysql-app:
                 container_name: mysql_container
                 image: mysql
                 networks:
                      - flask-nw
                 environment:
                        MYSQL_ROOT_PASSWORD: pass123
                        MYSQL_DATABASE: testdb
                 volumes:
                      - mysql-volume:/docker-entrypoint-initdb.d       #  name of volume:/path of container 
                           

networks:
        flask-nw:             # name of network you want to create 
                external: true

volumes:
        mysql-volume:         # name of volume you want to create 
                driver: local
                driver_opts:
                        device: /home/chaitanya/projects/volume/flask_volume  # local (host) system path 
                        type: none
                        o: bind 
