version: '3'
services:
      flask-app:
                container_name: flask-container    
                image: chaitanya305/flask-image                      # to provide image name 
                build:
                    context: .
                ports:
                    - 5000:5000
                networks:
                    - flask-nw
                depends_on:
                     - mysql-app
           
      mysql-app:
                 container_name: mysql_container
                 image: mysql
                 networks:
                      - flask-nw
                 environment:
                        MYSQL_ROOT_PASSWORD: pass123
                        MYSQL_DATABASE: testdb
                 volumes:
                      - ./message.sql:/docker-entrypoint-initdb.d/message.sql     #  host_path:/path of container 
                           

networks:
        flask-nw:           
            
