apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql
        imagePullPolicy: Never
        name: mysql
        volumeMounts:
          - name: mysql-vm
            mountPath: /docker-entrypoint-initdb.d
        envFrom:
          - configMapRef:
              name: mysql-cm
          - secretRef:
              name: mysql-secret
        ports:
          - containerPort: 80 
      volumes:
      - name: mysql-vm
        persistentVolumeClaim:
            claimName: mysql-pvc
