apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-pv
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    storageClassName: ""
    volumeMode: Filesystem
    hostPath:
          path: /home/chaitanya/projects/volume/flask_volume
